# Generated by Django 5.1 on 2026-06-19 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('invitation_sent', 'Invitation Sent'), ('application_received', 'Application Received'), ('joined', 'Joined'), ('declined', 'Declined')], default='invitation_sent', max_length=30)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField()),
            ],
        ),
    ]
